package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

func TaskMaker(ctx context.Context, query string, tools []ToolDefinition) (string, error) {
	systemprompt := fmt.Sprintf(`
		You are a taskmaker agent.
		Your goal is to change user prompt into a good structured instruction stages that are detail and easily executed by the sub-agents.

		Output format:
			1. stages one \n
			2. stages two \n
			3. stages three \n
			4. .......
	`)
	messages := []Message{
		{
			Role:    "system",
			Content: systemprompt,
		},
		{
			Role:    "user",
			Content: query,
		},
	}

	maxIterations := 5
	for i := 0; i < maxIterations; i++ {
		res, err := ChatGenerate(ctx, messages, tools, 262144, GeneratorModel, 2)
		if err != nil {
			return "", fmt.Errorf("ChatGenerate error: %w", err)
		}

		messages = append(messages, Message{Role: "assistant", Content: res.RawOutput})
	}

	messages = append(messages, Message{Role: "user", Content: "Silakan berikan rangkuman akhir Anda sekarang berdasarkan informasi yang telah didapatkan."})
	finalRes, err := ChatGenerate(ctx, messages, nil, 262144, GeneratorModel, 2)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(finalRes.RawOutput), nil
}

func Orchestrator(ctx context.Context, query string, tools []ToolDefinition) (string, error) {
	// 1. Panggil TaskMaker untuk membuat tahapan kerja (stages)
	stages, err := TaskMaker(ctx, query, tools)
	if err != nil {
		return "", fmt.Errorf("TaskMaker error: %w", err)
	}
	fmt.Printf("\n=== [STAGES DARI TASKMAKER] ===\n%s\n===============================\n", stages)
	// 2. Orchestrator membaca stages, menentukan sub-agent yang tepat, dan menyusun query khusus
	systemPrompt :=
		`You are the Lead Orchestrator.
				You are given a list of stages generated by TaskMaker.
				Your Tasks:
					1. Look at each stage that needs to be done.
					2. Determine WHICH sub-agent is needed for that stage:
						- call_file_summarizer: to read, find, or analyze code/files.
						- call_code_fixer: to fix bugs or update code.
						- call_software_agent: to write new programs.
						- call_testing_agent: to test and run bash commands.
						- call_reviewer_agent: to review code quality.
						- call_documenter_agent: to write docs.
					3. Formulate a CLEAR and COMPLETE query specifically tailored for that sub-agent. Include any details or findings learned from previous stages.
					4. Call the sub-agent.
					5. Once all stages are done, provide your final response to the user without calling any tools.`
	messages := []Message{
		{Role: "system", Content: systemPrompt},
		{
			Role: "user",
			Content: fmt.Sprintf("User Request:\n%s\n\nStages from TaskMaker:\n%s\n\nSilakan tentukan sub-agent yang sesuai untuk tiap stage dan rumuskan query-nya.",
				query, stages),
		},
	}
	maxIterations := 100
	for i := 0; i < maxIterations; i++ {
		res, err := ChatGenerate(ctx, messages, SubAgentTools, 262144, GeneratorModel, 2)
		if err != nil {
			return "", err
		}
		calls := ParseToolCalls(res.RawOutput)
		if len(calls) == 0 {
			// Selesai jika Orchestrator tidak memanggil tool lagi
			return strings.TrimSpace(res.RawOutput), nil
		}
		messages = append(messages, Message{Role: "assistant", Content: res.RawOutput})
		// Eksekusi sub-agent yang dipilih oleh Orchestrator
		var subReports []string
		for _, tc := range calls {
			fmt.Printf("\n[Orchestrator] Memilih: %s\n", tc.Name)
			report, err := dispatchSubAgent(ctx, tc.Name, tc.RawArgs)
			if err != nil {
				subReports = append(subReports, fmt.Sprintf("Error from %s: %v", tc.Name, err))
			} else {
				subReports = append(subReports, fmt.Sprintf("Report from %s:\n%s", tc.Name, report))
			}
		}
		messages = append(messages, Message{
			Role: "user",
			Content: fmt.Sprintf("Hasil Sub-Agent:\n%s\n\nSilakan lanjutkan ke stage berikutnya atau berikan kesimpulan akhir jika semua stage selesai.",
				strings.Join(subReports, "\n\n---\n\n")),
		})
	}
	return "Batas iterasi orchestrator tercapai.", nil
}

// SubAgentTools mendefinisikan sub-agent yang dapat dipanggil oleh Orchestrator
var SubAgentTools = []ToolDefinition{
	{
		Type: "function",
		Function: ToolFunction{
			Name:        "call_file_summarizer",
			Description: "Panggil sub-agent ini jika stage membutuhkan pencarian file, pembacaan kode, atau analisis informasi.",
			Parameters: &FunctionParams{
				Type: "object",
				Properties: map[string]PropertySchema{
					"query": {Type: "string", Description: "Instruksi spesifik yang Anda rumuskan untuk FileSummarizer"},
				},
				Required: []string{"query"},
			},
		},
	},
	{
		Type: "function",
		Function: ToolFunction{
			Name:        "call_code_fixer",
			Description: "Panggil sub-agent ini jika stage membutuhkan perbaikan bug atau perubahan kode yang sudah ada.",
			Parameters: &FunctionParams{
				Type: "object",
				Properties: map[string]PropertySchema{
					"query": {Type: "string", Description: "Instruksi perbaikan dan konteks file/logika untuk CodeFixer"},
				},
				Required: []string{"query"},
			},
		},
	},
	{
		Type: "function",
		Function: ToolFunction{
			Name:        "call_software_agent",
			Description: "Panggil sub-agent ini jika stage membutuhkan pembuatan program/skrip/file baru dari awal.",
			Parameters: &FunctionParams{
				Type: "object",
				Properties: map[string]PropertySchema{
					"query": {Type: "string", Description: "Instruksi pembuatan program baru untuk SoftwareAgent"},
				},
				Required: []string{"query"},
			},
		},
	},
	{
		Type: "function",
		Function: ToolFunction{
			Name:        "call_testing_agent",
			Description: "Panggil sub-agent ini jika stage membutuhkan pembuatan unit test dan menjalankan perintah pengujian (bash).",
			Parameters: &FunctionParams{
				Type: "object",
				Properties: map[string]PropertySchema{
					"query": {Type: "string", Description: "Instruksi pengujian untuk TestingAgent"},
				},
				Required: []string{"query"},
			},
		},
	},
	{
		Type: "function",
		Function: ToolFunction{
			Name:        "call_reviewer_agent",
			Description: "Panggil sub-agent ini jika stage membutuhkan peninjauan kualitas atau review kode tanpa mengubah file.",
			Parameters: &FunctionParams{
				Type: "object",
				Properties: map[string]PropertySchema{
					"query": {Type: "string", Description: "Aspek yang perlu direview oleh ReviewerAgent"},
				},
				Required: []string{"query"},
			},
		},
	},
	{
		Type: "function",
		Function: ToolFunction{
			Name:        "call_documenter_agent",
			Description: "Panggil sub-agent ini jika stage membutuhkan pembuatan dokumentasi, panduan, atau README.",
			Parameters: &FunctionParams{
				Type: "object",
				Properties: map[string]PropertySchema{
					"query": {Type: "string", Description: "Topik dan bagian yang perlu didokumentasikan oleh DocumenterAgent"},
				},
				Required: []string{"query"},
			},
		},
	},
}

// dispatchSubAgent menjalankan sub-agent sesuai pilihan Orchestrator
func dispatchSubAgent(ctx context.Context, toolName string, argsJSON string) (string, error) {
	var params struct {
		Query string `json:"query"`
	}
	if err := json.Unmarshal([]byte(argsJSON), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	switch toolName {
	case "call_file_summarizer":
		return FileSummerizer(ctx, params.Query, nil)
	case "call_code_fixer":
		return CodeFixer(ctx, params.Query, nil)
	case "call_software_agent":
		return SoftwareAgent(ctx, params.Query, nil)
	case "call_testing_agent":
		return TestingAgent(ctx, params.Query, nil)
	case "call_reviewer_agent":
		return ReviewerAgent(ctx, params.Query, nil)
	case "call_documenter_agent":
		return DocumenterAgent(ctx, params.Query, nil)
	default:
		return "", fmt.Errorf("sub-agent tidak dikenal: %s", toolName)
	}
}
